### ISSUE TITLE
lost connection after 20 min. when Thermostat included

### ISSUE THREAD

**Issue by benbeton** [SphtKr/homebridge-zway#11]
Hi,
recently I added "Danfoss Thermostats" to z-wave. After adding, they are working fine. But after about 20 minutes I have to no connection to homebridge anymore.
Only if I change name and ID in the confighomebridge is accessable for a few minutes. 

When using ```"opt_in"``` and tagging all but the thermostats with ```"Homebridge.Include"``` homebrdige is working fine.
tagging the thermostats with ```"Homebridge.Skip"``` does not work. (the are still included )

what logs or data can I provide to get closer to the problem?

regards

**Comment by SphtKr** [comment]
Hello,

These are the Danfoss "Living Connect" thermostats that attach to a radiator valve, correct? I have some of these myself, so that's good. But they're behaving fine for me...however I have not upgraded my Z-Way server (on RaZBerry) to 2.2 yet--I am guessing you may be having trouble with them because of a change in 2.2, is that the version of Z-Way you are running?

The problem with `Skip` has just been resolved (I think) in release 0.3.3 of homebridge-zway, just a few days ago. Can you do a `npm list -g homebridge-zway` and see if you're on 0.3.3, and if not, do `npm upgrade -g homebridge-zway`?

Next, can you do the following:

Run homebridge with debugging turned on: `DEBUG=* homebridge` and attach the output here.

Login to the Z-Way standard UI, and then hit `http://your.pi.i.p:8083/ZAutomation/api/v1/devices` (replacing your.pi.i.p with your Z-Way server's IP address of course), and attach or post the contents here.

Also, hit the `/accessories` endpoint of your homebridge server (probably `http://your.homebridge.i.p:51826/accessories`) and attach the contents of that here. If you can do that twice, once before you get disconnected, and then again shortly after, that would probably be helpful too.

**Comment by benbeton** [comment]
Hi,

yes, these are the Danfoss "Living Connect" thermostats. 
I'm running Z-Way 2.2 on a RaZberry.

At first I will upgrade to version 0.3.3 (still running 0.3.2) and do some more testing (tags and if the error still exist)
If yes, I'll provide the needed logs this evening or tomorrow.

thank you for you help!

**Comment by SphtKr** [comment]
Great! Do let me know!

**Comment by benbeton** [comment]
Hi,

unfortunately the issue happen again. 

accessories, when the issue is happening (http://pastebin.com/bXRkpReq)
accessories, when its working (http://pastebin.com/ms1yNxBx)

my zwave api output (http://pastebin.com/9LW0QUxk) 

homebridge debug log: (http://pastebin.com/pUPDTFzs)

I've checked the logs but I do not see any errors there, maybe you can

**Comment by SphtKr** [comment]
Okay looking into it. Curious...have you also added the ThinkingCleaner plugin just recently?

**Comment by benbeton** [comment]
I haven't added it recently, but could be possible that the last update changed something. It seams to be related to the "ThinkingCleaner plugin" I disabled it and the thermostats are working when included. no issue anymore. 

I did a lot of testing today, seems to work without the ThinkingCleaner plugin.

Thank you for your help and for developing this plugin!

**Comment by SphtKr** [comment]
Ah, thanks. I noticed something in the Roomba device that might be causing a problem, so that's why I asked. If you contact the developer of that plugin, I think the problem is that he's sometimes returning a string `"0"` instead of a numeric `0` or `false` when it's "off", it's this segment:

```
        {
          "iid": 7,
          "type": "00000049-0000-1000-8000-0026BB765291",
          "characteristics": [
            {
              "iid": 8,
              "type": "00000023-0000-1000-8000-0026BB765291",
              "perms": [
                "pr"
              ],
              "format": "string",
              "value": "Roomba",
              "description": "Name"
            },
            {
              "iid": 9,
              "type": "00000025-0000-1000-8000-0026BB765291",
              "perms": [
                "pr",
                "pw",
                "ev"
              ],
              "format": "bool",
              "value": "0",
              "description": "On"
            }
          ]
        }
```
