### ISSUE TITLE
AEON LABS MULTISENSOR 6 - only return Temp or isPrimary 

### ISSUE THREAD

**Issue by rudders** [SphtKr/homebridge-zway#2]
Hi - I have a AEON LABS MULTISENSOR 6 and no matter what I try I can only get one accessory to load into homebridge - well I get temp and lux in a single accessory. Here's the data you ask for. If is set isPrimary to the burglar sensor that will be found but the others go away - suspect I just haven't read you documentation enough times to figure it out.

[Archive.zip](https://github.com/SphtKr/homebridge-zway/files/83106/Archive.zip)

**Comment by SphtKr** [comment]
Thanks, that input is great. There are a couple of things here, some which require fixes, others that you can adjust settings for...

1. Set these tags on the motion sensor device in Z-Way:
    `Homebridge.IsPrimary`
    `Homebridge.Service.Type:MotionSensor`
    `Homebridge.Characteristic.Type:MotionDetected`
that should get your motion sensor working. Part of the issue here is that Z-Way only reports motion sensors (so far as I've seen) as `sensorBinary`, which is too vague to process, so Homebridge has to be told that it's a motion sensor.

2. I haven't built Humidity or UV Index sensor support in yet. Now I have an example, thanks!

3. It looks like it's reporting two additional sensors that are tamper and/or vibration. Not sure what the difference is. But you can put the tag `Homebridge.Characteristic.Type:StatusTampered` on the one that's appropriate

4. The Battery level should work properly...it may be reported in a different place in the app though. In Eve for instance you don't see it as a device category on the main screen unless you enable that category for display in settings--though you should see it if you look in "At a Glance" though.

5. The Lux sensor may or may not work right...does it seem to show the right values? Up until today I only had some Devolo light sensors that report in percent--I just opened a Fibaro sensor that reports in Lux though, so I'm going to use that as a baseline to improve the %->Lux conversion formula that is just broken right now. But I'm not sure if Lux units will be passed through properly, let me know!

**Comment by rudders** [comment]
Thanks,
1. If I set the motion as primary then the temperature and lux do not get picked up ;(
2. Pleasure! 
3. Will take a closer look - Motion, Temp, Lux, Hum are the priorities.
4. Plugged in currently.
5. Lux seems work

Thanks!

**Comment by SphtKr** [comment]
Ah.....I noticed with your motion sensor and my new Fibaro that both qualify themselves as "General purpose" in the probeTitle :confounded: , which meant it was being skipped. I also threw in untested Humidity sensor support. Can you try [this branch](https://github.com/SphtKr/homebridge-zway/tree/fix-aeon-multi-and-fibaro-motion)--either download the zip or clone it, and run `npm install -g` inside the directory--and see if that fixes the motion sensor and Humidity sensor?
