### ISSUE TITLE
Dimmer: if set to 5% or lower raptors off value

### ISSUE THREAD

**Issue by zeair** [SphtKr/homebridge-zway#31]
If i set my dimmer (Fibaro FGD-212) to 5% or lower an off status is reported to homekit application. Z-way web UI shows it as on. Any ideas how to change whether my bulb is set 1% to have ON status reported?

**Comment by SphtKr** [comment]
Hello, Yes, that was by design--originally at least. It was done that way to address a flaw in Z-Way where a dimmer might not register it's last "0%" value. But a later version (2.1?) fixed that by polling all dimmers until they stopped updating.

I also thought I made that threshold configurable, but apparently I did not. I will make that a feature.

**Comment by zeair** [comment]
Thanks! I'm looking forward, since I have very bright LED bulbs my entire house works at 1% on the evenings and this is really painful for me. I had to create Turn off scenes to have handy control on iphone notification center to turn them off.

**Comment by zeair** [comment]
Thank you great man! Works like a charm :)
