### ISSUE TITLE
What's the easiest hardware-path to make this work?

### ISSUE THREAD

**Issue by archpoint** [SphtKr/homebridge-zway#40]
I'm fairly new to both Homekit and Z-wave but I've decided to standardize everything with Homekit and so far Homebridge is perfectly integrating all my non-Homekit devices. However, I am looking to buy a smart lock and the only native homekit supported lock I've found is August Smart Lock but it's not compatible with Scandinavian locks at all.

So I found a lock called Danalock which supports Z-Wave, and I've realized that I could use this homebridge plugin to integrate the lock with Homebridge as you've already added support for the Danalock (good work!). However, what's the most painless path in terms of hardware. Would a RaZberry be all I need? Would the lock communicate with the RaZberry through Z-wave and this homebridge plugin could then communicate with the RaZberry? 

Apologies for the noobiness here but I'd really like to figure this out :)

**Comment by SphtKr** [comment]
Yes, what you've got there is probably the most straightforward way.

Of note though, I just got my Raspberry Pi v3--and when I slapped my Razberry board on, discovered that in order to get it to work on that hardware you have to disable the RPi3's onboard Bluetooth!

Disabling Bluetooth is not too hard, but it's a pain if you didn't know about it. You can: A: do that, B: find a deal on a RPi2 or Model B+ instead, C: buy an RPi3 and Z-Wave.me's USB module instead (just be sure to get the version that includes a Z-Way license). Any of those will work, each obviously has its pros and cons. I'd go with option A, or C if you anticipate wanting the onboard Bluetooth.
