### ISSUE TITLE
Fibaro Motion Sensor configuration (FGMS-001)

### ISSUE THREAD

**Issue by archpoint** [SphtKr/homebridge-zway#42]
Hi.

I believe you mentioned here somewhere that you have the Fibaro motion sensor as well. How have you configured it with home bridge? Currently the motion alarm doesn't show up and if I add the tags described in the README I loose the temperature and lumin devices and the alarm device doesn't seem to work anyway.

Advice would be greatly appreciated.

**Comment by SphtKr** [comment]
Hmm... Well, to answer your question, on the motion _sensor_ device I have:

`Homebridge.Characteristic.Type:MotionDetected` `Homebridge.IsPrimary` `Homebridge.Service.Type:MotionSensor`

On the _tamper_ sensor, I have:

`Homebridge.Characteristic.Type:StatusTampered`

And that's about it, nothing of consequence on the temperature or light sensors (`Homebridge.Include`, but I think that's because I was doing something in my dev environment).

I'm unsure whether when you say the "motion alarm" you're talking about the PIR motion sensor device, or the tamper sensor (which uses an accelerometer to detect motion of the device itself). I think what I'm calling the tamper sensor is what's recognized by Z-Way as implementing the "AlarmSensor" class, and uses the accelerometer. Is that the device you're referring to?

**Comment by Zyg0te** [comment]
I'm not really concerned with the tamper alarm, it's the motion sensor I'm struggling with. What firmware version of the FGMS-001 do you have? From what I've been able to gather, the new version that I have, 3.20, is a bit different than the older ones and no longer works all that well out of the box with Z-Way. No motion alarms show up at all in Z-way and I had to tinker with associations on the device to get anywhere. It's probably a Z-Way issue as well though as it now thinks the motion alarm is some sort of switch.

Could you check your motion sensor firmware version and go to the Z-way expert UI and look at the device associations? What does it look like for you? Maybe I just got mine all wrong.

Thanks!

**Comment by Zyg0te** [comment]
I added an association between the motion group and the z-way controller and I now get a remote device in Z-way that correctly indicates motion detection. So it's obviously a bit buggy considering it's the completely wrong device type but at least it works. However, your plugin doesn't seem to support remote devices currently so I'm a bit stuck.

**Comment by osxdoc** [comment]
I have the same problem with FGMS-001 and 3.20 Firmware, Im miss the Motion sensor.
Please explain how to add it?

**Comment by SphtKr** [comment]
All on this thread: I found a bug when I was working on 0.5.0-alpha4 that may have affected any Sensor that Z-Way reports as "general purpose", including many motion sensors. Can you folks try the latest release (alpha4) and see if it happens to improve or change your issue? Thanks!

**Comment by SphtKr** [comment]
Believe this is fixed in 0.5.0-alpha4 and 0.5.0-rc0...reopen or submit new issue if this still isn't working.
