### ISSUE TITLE
Homebridge-Zway and Apple TV 4

### ISSUE THREAD

**Issue by MatsA** [SphtKr/homebridge-zway#54]
Hi !

Great work You are doing !

I started up with HomeKit and the iOS Home app with the products from https://www.elgato.com/en/eve. So a Apple TV 4 is configured as the home hub together with one EVE Room, indoor sensor, and one Eve Energy, everything works nice, remote and scheduled events.

Then I installed the Razberry solution together with Your software and Homebridge. All documented at http://pysselilivet.blogspot.com/2016/10/homekit-bridge-for-z-wave.html and a Z-wave switch.

The switch shows in the iOS Home app and You can switch it on/off online.
But, when You not are connected to the same Wifi it doesnt work. The same is with à scheduled event, it doesnt work

Any ideas ? Anything wrong with installation ? 

The Z-switch is working via the scheduler in the Razberry solution.

[accessories.txt](https://github.com/SphtKr/homebridge-zway/files/523970/accessories.txt)
[devices.txt](https://github.com/SphtKr/homebridge-zway/files/523972/devices.txt)

Best Regards Mats

**Comment by SphtKr** [comment]
Ugh, no idea...So, before iOS 10, they let you use an AppleTV 3--which I have--and that worked just fine and I'm pretty sure it did for others. I don't have an AppleTV 4 to test, and I'm waiting to see if there's a 5th-gen or new device that comes out before the end of the year...but until then I can't say what's up, unless anyone else can chime in and say this is working for them. I would have expected it to!

Well, then one idea occurs to me. Some folks (with HomeBridge in general) have had problems with Bonjour operating properly on their home network. It may be that your iPhone can properly communicate with your Homebridge installation, but your AppleTV can't. Are they both on wireless or is the AppleTV wired? Same IP address subnet? In the case of the Eve devices they're all bluetooth (I think) so WiFi/Ethernet/IP wouldn't matter. Unless the AppleTV and your iPhone are both wireless and on the same IP, I might try messing with the AppleTV's network config and see if anything helps (move it from wired to Wireless, try and make it use 2.4GHz instead of 5GHz, etc.).

**Comment by MatsA** [comment]
HI ! 

Thanks for your response and engagement !

I’m not religious but……..

Yesterday I had a lunch with a friend and showed him the HomeKit iOS app Home, on my iPhone and a 4G connection, and to my surprise the Z-Wave switch showed in the app and there was a connection. So when I came home I scheduled a timer job and it all worked ! 

I haven’t done any changes …. so what have happened I dont know ?

The ATV and RPi are both wired and on the same subnet. Yes correct, the Eve devices are BLE.

Any ideas ?

/Mats

**Comment by SphtKr** [comment]
No ideas really, but when the AppleTV 3 hub capability first came out, folks had a good deal of trouble figuring out how to make it cooperate...bunch of stuff about turning off iCloud on the device and turning it back on again, other possible voodoo weirdness, and then it would just start working. You may have just not waited long enough.
