### ISSUE TITLE
Wrong Status of Fibaro Dimmers

### ISSUE THREAD

**Issue by TS-Tec** [SphtKr/homebridge-zway#59]
Hi!

Im using home bridge with Razberry and ZWay.

Following problem with the Fibaro Dimmers:
I tell Siri to set the dimmers to 1% - this works fine.
But the status of the lamps changes to "off" in HomeKit!
In the Razberry web frontend, the status is correct! 
What could be the root cause for this issue?

Thanks!!

**Comment by klaasjoerg** [comment]
Well, actually if you have a look at your fibaro dimmer definition/settings you will read the following:
You can set a dimmer value between 1%-99% where 1% is equally to off and 99% full state.
So I assume there is not really a problem, it's just a matter of different definition. And per definition it means that a value of 1% seems to be simply "off"....

**Comment by TS-Tec** [comment]
OK, then I have to precise this: It also does not work between 2% and 6%.
In the Razberry front end it shows the correct percentage. In Homekit it shows "off"...

**Comment by SphtKr** [comment]
Hi @TS-Tec ... Whoops! This is a documentation omission.

The behavior you're observing is a "feature", that was more necessary in Z-Way 2.1 (I think) and earlier, where a dimmer's final status would not always be properly reported--that is, if a dimmer started ramping down to 0%, it might appear stuck at some small percent in the Z-Way interface. They changed/fixed this behavior in Z-Way though, so it's a bit unnecessary now. 

You can change this behavior by setting a value for `dimmer_off_threshold` in `config.json`, and it sounds like you'll want to set it to `0`. I will update the documentation to include this feature, but it should work already, since the first 0.5.0-alpha release, I think. See also #31 and commit 3f1420e.

**Comment by TS-Tec** [comment]
@SphtKr That's it! Works fine now!
Can you tell what is the default value if this parameter is not set in config.json?

**Comment by SphtKr** [comment]
Yes, it's 5.
