### ISSUE TITLE
Quick question regarding Homebridge.Service.Type:....

### ISSUE THREAD

**Issue by klaasjoerg** [SphtKr/homebridge-zway#77]
If I define a tag for a virtual zwave.me device e.g for a toggle-button (or virtual-code device) or whatever:
For example I set  _Homebridge.Service.Type:Door_ or _GarageDoor_  for a code-device/switch.

Shouldn't Homebridge then make it appear as a "lock" instead of a switch in homekit?
In make case they are still always shown as ordinary switches, regardless of any type I tried.
Ideas?

**Comment by SphtKr** [comment]
At present it doesn't allow any and every combination of `Homebridge.Service.Type`, only the documented use-cases are allowed. This is/was because it was otherwise relatively easy to force Homebridge-zway into publishing a combination of Services/Characteristics that was illegal.

For instance if you created a GarageDoor without an ObstructionDetected Characteristic, HomeKit would flag the bridge as non-compliant. And when that happened you had to reset your HomeKit configuration (meaning all your devices, rooms, scenes, automations, everything would be deleted). 

This may have improved since nearly two years ago when we started this, but the answer is currently no, you can't do this, because it was too easy to mess things up.

**Comment by klaasjoerg** [comment]
Ah okay. Good to know. Can that behavior be read in apples HomeKit dev documentation or did you find out yourself?

**Comment by SphtKr** [comment]
The answer is I found out about it myself. Unsure if it's in Apple's documentation, I don't think I have access to where that would be, that kind of detail is probably only for device manufacturers.
